version: 2
jobs:
  build:
    docker:
      - image: itamararjuan/golang_with_node_aws
    steps:
      - checkout
      - run:
          command: bash test.sh
          environment:
            GOBIN: /usr/local/bin/

workflows:
  version: 2
  build:
    jobs:
      - build