version: 2
jobs:
  build:
    docker:
      - image: itamararjuan/golang_with_node_aws
    steps:
      - checkout
      - run: 
          command: ./.circleci/setup.sh
          environment:
            GOBIN: /go/bin/
      - run:
          command: ./test.sh
          environment:
            GOBIN: /go/bin/

workflows:
  version: 2
  build:
    jobs:
      - build